### ISSUE TITLE
Remove RedirectIfAuthenticated middleware

### ISSUE THREAD

**Issue by sineverba** [sineverba/laravel-backend#19]
Not necessary because it is a frontend middleware.

**Comment by arc92** [comment]
Ok if want do you want to happen when user not authenticated???

**Comment by sineverba** [comment]
You are right, but with API rest we don't need (or, at least, not me) to redirect. Simply, respond with a JSON message "Not authorizer" + 401 http status code.

**Comment by arc92** [comment]
sure you right, If you use rest API redirection doesn't mean.
if you have Application/json in header of request redirect doesn't happen.
also you can use Passport for Rest API authentication
